# Generated by Django 2.1.4 on 2018-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpontoturistico',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
