# Generated by Django 2.1.4 on 2018-12-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_auto_20181221_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpontoturistico',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.ModelAtracao'),
        ),
    ]
