# Generated by Django 2.1.4 on 2018-12-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_modelpontoturistico_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpontoturistico',
            name='comentario',
            field=models.ManyToManyField(to='comentarios.ModelComentarios'),
        ),
    ]
