# Generated by Django 2.1.4 on 2018-12-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_modelpontoturistico_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpontoturistico',
            name='avaliacao',
            field=models.ManyToManyField(blank=True, null=True, to='avaliacoes.ModelAvaliacao'),
        ),
    ]
