# Generated by Django 2.1.4 on 2018-12-26 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0005_modelpontoturistico_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpontoturistico',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.ModelEndereco'),
            preserve_default=False,
        ),
    ]
