# Generated by Django 2.1.4 on 2018-12-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modelpontoturistico_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpontoturistico',
            name='avaliacao',
            field=models.ManyToManyField(blank=True, to='avaliacoes.ModelAvaliacao'),
        ),
    ]
