# Generated by Django 2.1.4 on 2019-01-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181226_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpontoturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ponto_turistico'),
        ),
    ]
