# Generated by Django 2.1.4 on 2018-12-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelatracao',
            old_name='horatio_func',
            new_name='horario_func',
        ),
    ]
